name: 'Snowplow Data Structures CI - Check'
description: 'Verify that all of your app''s data structures dependencies are already deployed into the specified environment'
author: 'Snowplow Analytics'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  organization-id:
    description: 'UUID of the Snowplow organization as found in Snowplow Console'
    required: true
  api-key-id: 
    description: 'Snowplow Console API key ID'
    required: true
  api-key: 
    description: 'Snowplow Console API key'
    required: true
  manifest-path:  
    description: 'Absolute path to the manifest file describing data structures dependencies of your app'
    required: true
    default: 'snowplow-schemas.json'
  environment: 
    description: 'The environment against which the check is performed'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Download data-structures-ci tool
      shell: bash
      run: |
        curl -L "https://github.com/snowplow-product/msc-schema-ci-tool/releases/download/2.0.0/data_structures_ci_2.0.0.zip" -o data_structures_ci.zip
        unzip data_structures_ci.zip
        chmod +x ./data-structures-ci
    - name: Run check
      shell: bash
      env:
        ORGANIZATION_ID: ${{ inputs.organization-id }}
        API_KEY_ID: ${{ inputs.api-key-id }}
        API_KEY: ${{ inputs.api-key }}
      run: |
        ./data-structures-ci check \
          --manifestPath "${{ inputs.manifest-path }}" \
          --environment "${{ inputs.environment }}"